services:
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    volumes:
      - '.:/home/node/app'
      - '.zsh_history:/home/node/.zsh_history'
    ports:
      - '8080:8080'
